const data = {
  productData: [
    {
      id: 1,
      title: "Cotton Polo Tees",
      desc: "Vintage Font Signage Tees Font Signage Tees",
      price: 399,
      crossprice: 1399,
      src: "/images/product/__344X377-18.jpg",
      link: "https://www.amazon.in/REVOLT-Cotton-T-Shirt-Branding-REVSS23-POL-002/dp/B0C5RKHWRH?ref_=ast_sto_dp&th=1&psc=1",
    },
    {
      id: 2,
      title: "Full Sleeve Tees",
      desc: "Vintage Font Signage Tees Font Signage Tees",
      price: 299,
      crossprice: 1399,
      src: "/images/product/__344X377-19.jpg",
      link: "https://www.amazon.in/REVOLT-Comfortable-T-Shirt-Full-Branding-REVSS23-TEE-009/dp/B0C5RKJRS3?ref_=ast_sto_dp&th=1&psc=1",
    },
    {
      id: 3,
      title: "Graphic Print Tees",
      desc: "Vintage Font Signage Tees Font Signage Tees",
      price: 699,
      crossprice: 1499,
      src: "/images/product/__344X377-20.jpg",
      link: "https://www.amazon.in/REVOLT-Casual-Cotton-T-Shirt-Photographic-REVSS23-GRA-001/dp/B0C5RH63V1?ref_=ast_sto_dp&th=1&psc=1",
    },
    {
      id: 4,
      title: "Synthetic Round Neck Tees",
      desc: "Vintage Font Signage Tees Font Signage Tees",
      price: 499,
      crossprice: 1699,
      src: "/images/product/__344X377-21.jpg",
      link: "https://www.amazon.in/REVOLT-Comfortable-T-Shirt-Gradation-Branding-REVSS23-TEE-011/dp/B0C5RLMJBB?ref_=ast_sto_dp&th=1&psc=1",
    },
    {
      id: 5,
      title: "Round Neck Cotton Tees",
      desc: "Vintage Font Signage Tees Font Signage Tees",
      price: 699,
      crossprice: 1399,
      src: "/images/product/__344X377-22.jpg",
      link: "https://www.amazon.in/REVOLT-Casual-Cotton-T-Shirt-Shoulder-REVSS23-TEE-003/dp/B0C5RJ42CW?ref_=ast_sto_dp&th=1&psc=1",
    },
    {
      id: 6,
      title: "Synthetic Polo Tees",
      desc: "Vintage Font Signage Tees Font Signage Tees",
      price: 699,
      crossprice: 1399,
      src: "/images/product/__344X377-23.jpg",
      link: "https://www.amazon.in/REVOLT-Comfortable-T-Shirt-Branding-REVSS23-POL-004/dp/B0C5RKBVDJ?ref_=ast_sto_dp&th=1&psc=1",
    },
    {
      id: 7,
      title: "Round Neck Cotton Tees",
      desc: "Vintage Font Signage Tees Font Signage Tees",
      price: 699,
      crossprice: 1399,
      src: "/images/product/__344X377-24.jpg",
      link: "https://www.amazon.in/REVOLT-T-Shirt-Graphic-Branding-REVSS23-TEE-002/dp/B0C5RJ5BN9?ref_=ast_sto_dp&th=1&psc=1",
    },
  ],
};

export default data;
