// export const BATTERY_RECHARGE_HISTORY_REQUEST = 'BATTERY_RECHARGE_HISTORY_REQUEST';
// export const BATTERY_RECHARGE_HISTORY_SUCCESS = 'BATTERY_RECHARGE_HISTORY_SUCCESS';
// export const BATTERY_RECHARGE_HISTORY_FAIL = 'BATTERY_RECHARGE_HISTORY_FAIL';
