export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LIST_RESET = "PRODUCT_LIST_RESET";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";

export const ALL_PRODUCT_DETAILS_REQUEST = "ALL_PRODUCT_DETAILS_REQUEST";
export const ALL_PRODUCT_DETAILS_SUCCESS = "ALL_PRODUCT_DETAILS_SUCCESS";
export const ALL_PRODUCT_DETAILS_FAIL = "ALL_PRODUCT_DETAILS_FAIL";
export const ALL_PRODUCT_DETAILS_RESET = "ALL_PRODUCT_DETAILS_RESET";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_REVIEW_CREATE_REQUEST = "PRODUCT_REVIEW_CREATE_REQUEST";
export const PRODUCT_REVIEW_CREATE_SUCCESS = "PRODUCT_REVIEW_CREATE_SUCCESS";
export const PRODUCT_REVIEW_CREATE_FAIL = "PRODUCT_REVIEW_CREATE_FAIL";
export const PRODUCT_REVIEW_CREATE_RESET = "PRODUCT_REVIEW_CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";

export const PRODUCT_CATEGORY_LIST_REQUEST = "PRODUCT_CATEGORY_LIST_REQUEST";
export const PRODUCT_CATEGORY_LIST_SUCCESS = "PRODUCT_CATEGORY_LIST_SUCCESS";
export const PRODUCT_CATEGORY_LIST_FAIL = "PRODUCT_CATEGORY_LIST_FAIL";

export const STATE_CITY_HUB_REQUEST = "STATE_CITY_HUB_REQUEST";
export const STATE_CITY_HUB_SUCCESS = "STATE_CITY_HUB_SUCCESS";
export const STATE_CITY_HUB_FAIL = "STATE_CITY_HUB_FAIL";

export const STATE_CITY_HUB_UPGRADE_REQUEST = "STATE_CITY_HUB_UPGRADE_REQUEST";
export const STATE_CITY_HUB_UPGRADE_SUCCESS = "STATE_CITY_HUB_UPGRADE_SUCCESS";
export const STATE_CITY_HUB_UPGRADE_FAIL = "STATE_CITY_HUB_UPGRADE_FAIL";

export const STATE_CITY_HUB_SC_REQUEST = "STATE_CITY_HUB_SC_REQUEST";
export const STATE_CITY_HUB_SC_SUCCESS = "STATE_CITY_HUB_SC_SUCCESS";
export const STATE_CITY_HUB_SC_FAIL = "STATE_CITY_HUB_SC_FAIL";

export const BOOKING_LEAD_LSQ_REQUEST = "BOOKING_LEAD_LSQ_REQUEST";
export const BOOKING_LEAD_LSQ_FAILED = "BOOKING_LEAD_LSQ_FAILED";
export const BOOKING_LEAD_LSQ_SUCCESS = "BOOKING_LEAD_LSQ_SUCCESS";
