export const VENDOR_DETAILS_REQUESTED = "VENDOR_DETAILS_REQUESTED";
export const VENDOR_DETAILS_FAILED = "VENDOR_DETAILS_FAILED";
export const VENDOR_DETAILS_RESET = "VENDOR_DETAILS_RESET";
export const VENDOR_DETAILS_SUCCESS = "VENDOR_DETAILS_SUCCESS";
