// bikeData.js
export const bikeData = {
    'RV1+': {
        range: "100 kms (Eco Mode), 80 kms (Normal Mode), 60 kms (Sports Mode)",
        topSpeed: "75 km/h",
        normalCharging: "2 hr 45 min",
        fastCharging: "0-80% in 1 hr 30 min",
        batteryCapacity: "2.0 KWh",
        weight: "105 Kg",
        appSupport: "-",
        color: "Red",
        brakes: "Front Disc 220mm / Rear Disc 220mm",
        tyres: "Front 80/90 R17 - Rear 90/80 R17",
        frontFork: "Telescopic Forks",
        rearSuspension: "Monoshock",
        batteryType: "Lithium Ion",
        motor: "Peak 3.5KW-(Hub Motor)",
        wheelBase: "1350mm",
        seatHeight: "790mm",
        carryingCapacity: "2 Persons/Maximum 250Kg",
        lighting: "LED Head Lamp,- Tail Lamps,- Indicators and Licence Plate Light-(All LED)",
        groundClearance: "180 mm",
        productWarranty: "5 years or 75,000 Kilometres *,- whichever occurs first.",
        batteryWarranty: "5 years or 75,000 Kilometres *,- whichever occurs first.",
        chargerWarranty: "2 years only, from the date of purchase.",
        ignitionType: "Mechanical Key",
        price:"₹99,990/ -",
    },
    'RV1': {
        range: "100 kms (Eco Mode), 80 kms (Normal Mode), 60 kms (Sports Mode)",
        topSpeed: "75 km/h",
        normalCharging: "2 hrs 15 min",
        fastCharging: "-",
        batteryCapacity: "2.2 KWh",
        weight: "108 Kg",
        appSupport: "-",
        color: "Red",
        brakes: "Front Disc 240mm / Rear Disc 240mm (CBS)",
        tyres: "Front 90/80~17 - Rear 110/80~17",
        frontFork: "Telescopic Forks",
        rearSuspension: "Twin Shocker",
        batteryType: "Lithium Ion",
        motor: "Peak 2.8KW-(Mid Drive)",
        wheelBase: "1350mm",
        seatHeight: "790mm",
        carryingCapacity: "2 Persons/Maximum 250Kg",
        lighting: "LED Head Lamp,- Tail Lamp, -Indicators and Licence Plate Light-(All LED)",
        groundClearance: "180 mm",
        productWarranty: "5 years or 75,000 Kilometres *,- whichever occurs first.",
        batteryWarranty: "5 years or 75,000 Kilometres *,- whichever occurs first.",
        chargerWarranty: "2 years only, from the date of purchase.",
        ignitionType: "Mechanical Key",
        price:"₹84,990/ -",
    },
    'RV400': {
        range: "150 kms (Eco Mode), 100 kms (Normal Mode), 80 kms (Sports Mode)",
        topSpeed: "85 km/h",
        normalCharging: "2 hr 15 min",
        fastCharging: "0-80% in 1 hr 20 min",
        batteryCapacity: "2.2 KWh",
        weight: "108 Kg",
        appSupport: "-",
        color: "Black",
        brakes: "CBS (Front Disc 240mm / Rear Disc 240mm)",
        tyres: "Front 90/80 R17 - Rear 110/80 R17",
        frontFork: "Upside Down Forks",
        rearSuspension: "Monoshock (Adjustable)",
        batteryType: "Lithium Ion",
        motor: "Peak 4.1KW-(Mid Drive)",
        wheelBase: "1350mm",
        seatHeight: "815 mm",
        carryingCapacity: "2 Persons/Maximum 150Kg",
        lighting: "LED Head Lamp-(Projection for High beam), -Tail Lamps And Indicators-(All LED)",
        groundClearance: "200 mm",
        productWarranty: "5 years or 75,000 Kilometres *,- whichever occurs first",
        batteryWarranty: "5 years or 75,000 Kilometres *,- whichever occurs first.",
        chargerWarranty: "2 years only, from the date of purchase.",
        ignitionType: "Mechanical Key",
        price:"₹1,36,950/ -",
    },
    'RV400BRZ': {
        range: "150 kms (Eco Mode), 100 kms (Normal Mode), 80 kms (Sports Mode)",
        topSpeed: "85 km/h",
        normalCharging: "2 hr 30 min",
        fastCharging: "0-80% in 1 hr 20 min",
        batteryCapacity: "3.24 KWh",
        weight: "110 Kg",
        appSupport: "included",
        color: "Blue",
        brakes: "CBS (Front Disc 240mm / Rear Disc 240mm)",
        tyres: "Front 90/80 R17 - Rear 110/80 R17",
        frontFork: "Upside Down Forks",
        rearSuspension: "Monoshock (Adjustable)",
        batteryType: "Lithium Ion",
        motor: "Peak 4.1KW-(Mid Drive)",
        wheelBase: "1350mm",
        seatHeight: "815 mm",
        carryingCapacity: "2 Persons/Maximum 150Kg",
        lighting: "LED Head Lamp-(Projection for High beam), -Tail Lamps And Indicators-(All LED)",
        groundClearance: "200 mm",
        productWarranty: "5 years or 75,000 Kilometres *,- whichever occurs first",
        batteryWarranty: "5 years or 75,000 Kilometres *,- whichever occurs first.",
        chargerWarranty: "2 years only, from the date of purchase.",
        ignitionType: "Mechanical Key",
        price:"₹1,25,450/ -",
    }
};
